### ISSUE TITLE
Not working on v3.0.

### ISSUE THREAD

**Issue by YeisonHunt** [simonhaenisch/hyper-fading-scrollbar#2]
Can you give me your preferences hyper.js file? Maybe there is a conflic with another package.

**Comment by simonhaenisch** [comment]
It's working for me on macOS with Hyper version 3.0.2. Here's my config file:

```js
/**
 * @see https://hyper.is#cfg
 */
module.exports = {
	config: {
		fontFamily: '"SF Mono", "Source Code Pro", Menlo, monospace',
		fontSize: 11,

		cursorShape: 'UNDERLINE',
		cursorBlink: true,

		scrollbarColor: 'dimgray',

		env: {},

		bell: false,
		copyOnSelect: true,
	},

	plugins: ['hyper-named-css-colors', 'hyper-fading-scrollbar'],
	localPlugins: [],
	keymaps: {},
};
```

Which version of `hyper-fading-scrollbar` do you have installed? Could you please describe how exactly it is not working? And can you check Hyper's console for any error logs?

Have you already tried using the `scrollbarColor` config option? Because (see readme):

> You may want to make sure that your color theme package comes first in the `config.plugins` array in `.hyper.js`, so that the right color is applied to the scrollbar (it is inherited from the `borderColor` setting by default).

**Comment by YeisonHunt** [comment]
Thanks for the config file, it was an error of mine and a restart was needed. :D
